# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
